## MySQL Configuration
#
#spring.datasource.url=jdbc:mysql://localhost:3306/gamekeys?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.database=MYSQL
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
##server.port=8080
#
#logging.level.root=INFO
#logging.level.org.springframework.web=debug
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false


spring:
  #  mvc:
  #    format:
  #      date: dd/MM/yyyy
  #      date-time: yyyy-MM-dd HH:mm:ss
  #      time: HH:mm:ss
  jackson:
    date-format: dd/MM/yyyy
    time-zone: Europe/Bucharest

  datasource:
    url: jdbc:mysql://localhost:3306/gamekeys?createDatabaseIfNotExist=true #database url
    password: root #database username
    username: root #database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        globally_quoted_identifiers: true



#        spring: web-application-type=none
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false
